---
- name: test1
  hosts: all
  tasks:
    - name: copy_file
      copy:
        src: /root/123
        dest: /root
    - name: packaging_module
      apt:
        name: git
        state: latest
      when: ansible_os_family == "Debian"    
- include: ansible1.yml    
