- name: copyplaybook
  hosts: all
  become: yes
  tasks:
    - name: copy_file
      copy:
        src: /root/one.txt
        dest: /root
    - name: packaging_module
      apt:
        name: "{{ item }}"
        state: latest
      with_items:
        - git
        - wget
        - maven
        - default-jre
    - name: shell_commands
      shell: ls /root
      register: target_ls
      shell: cat one.txt
      register: target_cat
    - debug:
        var: target_ls.stdout_lines
        var: target_cat.stdout_lines
      tags:
        - debug
        - shell
        - apt
        - copy  
